name: Publish package to GitHub Packages
on: push
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
        
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Publish package
        run: ./gradlew uploadArchives
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}